
version: 2

models:
  - name: customers
    description: "customers view"
    columns:
      - name: customerid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null